development:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASS}@/${MYSQL_DBNAME}?parseTime=true
  dir: test-migrations
  table: migrations

production:
  dialect: mysql
  datasource: ${MYSQL_USER}:${MYSQL_PASS}@tcp(localhost:3306)/${MYSQL_DBNAME}?parseTime=true
  dir: migrations
  table: migrations
